asd

diff --git a/.github/workflows/pull reqest.yaml b/.github/workflows/pull reqest.yaml
--- a/.github/workflows/pull reqest.yaml
+++ b/.github/workflows/pull reqest.yaml
@@ -71,38 +71,38 @@ jobs:
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}          
 
-    #   - name: Render Jinja2 template
-    #     uses: cuchi/jinja2-action@v1.2.2
-    #     with:
-    #       template: "./tf5/s3_template.j2"
-    #       output_file: "./tf5/${{ github.event.inputs.resource_name }}_main.tf"
-    #       variables: |
-    #         bucket_name=${{ github.event.inputs.bucket_name }}
+      - name: Render Jinja2 template
+        uses: cuchi/jinja2-action@v1.2.2
+        with:
+          template: "./tf5/s3_template.j2"
+          output_file: "./tf5/${{ github.event.inputs.resource_name }}_main.tf"
+          variables: |
+            bucket_name=${{ github.event.inputs.bucket_name }}
 
-    #   - name: Commit new Terraform file
-    #     run: |
-    #       UNIQUE_NAME="${{ github.event.inputs.resource_name }}"
-    #       MAIN_FILE="./tf5/${UNIQUE_NAME}_main.tf"
+      - name: Commit new Terraform file
+        run: |
+          UNIQUE_NAME="${{ github.event.inputs.resource_name }}"
+          MAIN_FILE="./tf5/${UNIQUE_NAME}_main.tf"
 
-    #       git config --local user.name "GitHub Actions"
-    #       git config --local user.email "actions@github.com"
+          git config --local user.name "GitHub Actions"
+          git config --local user.email "actions@github.com"
           
-    #       echo "Adding file: $MAIN_FILE"
-    #       if [ -f "$MAIN_FILE" ]; then
-    #         git add "$MAIN_FILE"
-    #         git commit -m "Add Terraform configuration for $UNIQUE_NAME"
-    #         echo "Pushing to branch: $BRANCH_NAME"
-    #         git push origin "$BRANCH_NAME"
-    #       else
-    #         echo "Error: $MAIN_FILE does not exist!"
-    #         exit 1
-    #       fi
+          echo "Adding file: $MAIN_FILE"
+          if [ -f "$MAIN_FILE" ]; then
+            git add "$MAIN_FILE"
+            git commit -m "Add Terraform configuration for $UNIQUE_NAME"
+            echo "Pushing to branch: $BRANCH_NAME"
+            git push origin "$BRANCH_NAME"
+          else
+            echo "Error: $MAIN_FILE does not exist!"
+            exit 1
+          fi
 
-    #   - name: Create pull request
-    #     uses: repo-sync/pull-request@v2
-    #     with:
-    #       destination_branch: main
-    #       pr_title: "Add new resource configuration for ${{ github.event.inputs.resource_name }}"
-    #       pr_body: "This PR adds a new Terraform configuration for resource ${{ github.event.inputs.resource_name }}"
-    #       pr_draft: false
-    #       github_token: ${{ secrets.GITHUB_TOKEN }}
+      - name: Create pull request
+        uses: repo-sync/pull-request@v2
+        with:
+          destination_branch: main
+          pr_title: "Add new resource configuration for ${{ github.event.inputs.resource_name }}"
+          pr_body: "This PR adds a new Terraform configuration for resource ${{ github.event.inputs.resource_name }}"
+          pr_draft: false
+          github_token: ${{ secrets.GITHUB_TOKEN }}
